defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] || 'react_contacts' %>
  password: <%= ENV['DB_PASS'] || 'react_contacts' %>
  host: localhost
  port: 5432

development:
  <<: *defaults
  database: react_contacts_development

test:
  <<: *defaults
  username: <%= ENV['TRAVIS'] ? 'postgres' : ENV['DB_USER'] || 'react_contacts' %>
  password: <%= ENV['TRAVIS'] ? '' : ENV['DB_PASS'] || 'react_contacts' %>
  database: react_contacts_test

production:
  <<: *defaults
  database: react_contacts_production
